WIP: First crack at origin calendar info for event
unl/UNL_Events pull request #135
Opened 2020-12-15 22:24 UTC by jsturek

2021-01-05 18:31 UTC, skoolbus39 requested changes

2021-01-05 18:31 UTC, skoolbus39 commented on www/templates/default/html/EventInstance/OriginCalendar.tpl.php
> +    <div class="dcf-mt-6 dcf-txt-2xs">
I suggest changing this to:
`<div><small class="dcf-txt-2xs">This event originated in <a href="<?php echo Controller::$url . urlencode($originCalendar->shortname); ?>"><?php echo $name; ?></a>.</small></div>`

2021-01-05 18:49 UTC, skoolbus39 approved these changes

2021-01-08 21:49 UTC, ericras approved these changes

2021-01-08 21:52 UTC, merged