Implement canceled event flagging and display
unl/UNL_Events pull request #156
Opened 2021-08-11 16:59 UTC by jsturek

2021-08-19 15:07 UTC, jsturek commented
@skoolbus39 and @ericras This PR is now ready for review and may be tested on https://events-dev.unl.edu.

2021-08-30 15:42 UTC, skoolbus39 requested changes

2021-08-30 15:42 UTC, skoolbus39 commented on src/UNL/UCBCN/Event.php
>  }
No newline at end of file

2021-08-30 15:49 UTC, skoolbus39 approved these changes

2021-08-31 20:43 UTC, ericras reviewed
"status" isn't a valid RSS element: https://validator.w3.org/feed/docs/rss2.html

I'd probably just change it to "category" - that might prohibit using "category" in the future for actual categories but maybe not. "Canceled" can always be a category kind of like a tag.

2021-09-01 17:37 UTC, jsturek commented
@ericras  I moved the cancel status to the description.  I don't think using category would be utilizing it as intended.

2021-09-01 19:38 UTC, ericras approved these changes

2021-09-01 19:42 UTC, merged