WIP: Refactor Auth and display frontend edit links
unl/UNL_Events pull request #159
Opened 2021-08-24 21:30 UTC by jsturek

2021-09-01 20:23 UTC, jsturek commented
@ericras and @skoolbus39 This is now ready for review and may be tested on https://events-dev.unl.edu.

2021-09-07 14:01 UTC, skoolbus39 requested changes
Looks good besides the no newline at end of file

2021-09-07 14:01 UTC, skoolbus39 commented on src/UNL/UCBCN/Manager/AuthAction.php
> +}
No newline at end of file

2021-09-07 14:32 UTC, jsturek commented on src/UNL/UCBCN/Manager/AuthAction.php
> +}
done

2021-09-07 15:40 UTC, skoolbus39 approved these changes

2021-09-07 19:42 UTC, ericras commented
https://events-dev.unl.edu/manager/https/manager/logout

Fatal error: Uncaught Error: Class name must be a valid object or a string in /var/www/html/events-dev.unl.edu/src/UNL/UCBCN/Manager/Controller.php:100 Stack trace: #0 /var/www/html/events-dev.unl.edu/src/UNL/UCBCN/Manager/Controller.php(50): UNL\UCBCN\Manager\Controller->run() #1 /var/www/html/events-dev.unl.edu/www/manager/index.php(25): UNL\UCBCN\Manager\Controller->__construct(Array) #2 {main} thrown in /var/www/html/events-dev.unl.edu/src/UNL/UCBCN/Manager/Controller.php on line 100

2021-09-07 19:47 UTC, ericras commented on www/templates/default/html/manager/navigation.tpl.php
> +            <?php endif; ?>
Prepend Util::getBaseURL() on this

2021-09-07 19:50 UTC, ericras commented on www/templates/default/html/manager/Controller.tpl.php
> +$page->addScriptDeclaration('WDN.setPluginParam("idm", "logout", "' .  Util::getBaseURL() . '/manager/logout");');
Somehow for this we're getting "https://events-dev.unl.edu/manager/https/manager/logout"

2021-09-07 19:52 UTC, ericras commented on www/templates/default/html/Controller.tpl.php
> +$page->addScriptDeclaration('WDN.setPluginParam("idm", "logout", "' . Util::getBaseURL() . '/manager/logout");');
Not generating the correct logout link. I'm getting "https://events-dev.unl.edu/TractorSafetyTraining/https/manager/logout"

2021-09-07 20:57 UTC, ericras commented on www/templates/default/html/manager/Controller.tpl.php
> +$page->addScriptDeclaration('WDN.setPluginParam("idm", "logout", "logout");');
Still does https://events-dev.unl.edu/manager/TractorSafetyTraining/logout on the manager side.  Probably still need to prepend a working base url string

2021-09-07 21:33 UTC, jsturek commented
@ericras ready for review

2021-09-07 21:54 UTC, ericras approved these changes

2021-09-08 14:11 UTC, merged